name: Code Linting and Checking

on:
  workflow_call:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        # prefer package script as it configures Prettier plugins
        run: npm run lint
  check:
    name: Check Svelte Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Check code
        # prefer package script as it configures tsconfig to check with
        run: npm run check
