name: Main Branch Continuous Integration and Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-lint-check:
    uses: ./.github/workflows/code-lint-check.yml
  vitest:
    needs: code-lint-check
    uses: ./.github/workflows/vitest.yml
  playwright:
    needs: code-lint-check
    uses: ./.github/workflows/playwright.yml
  deploy-prod:
    needs: [code-lint-check, vitest, playwright]
    # only deploy for branch push, not for pull requests
    if: github.event_name == 'push'
    uses: ./.github/workflows/vercel.yml
    with:
      production: true
