name: Vercel Deployments

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_call:
    inputs:
      production:
        description: 'Whether to deploy to production instead of a preview. Default is `false`.'
        type: boolean

jobs:
  vercel-deploy:
    name: Vercel Deploy ${{ inputs.production && '(Production)' || '(Preview)'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel environment information
        shell: bash
        run: vercel pull --yes --environment=${{ inputs.production && 'production' || 'preview' }} --token="$VERCEL_TOKEN"
      - name: Build project artifacts
        shell: bash
        run: vercel build ${{ inputs.production && '--prod' }} --token="$VERCEL_TOKEN"
      - name: Deploy project artifacts to Vercel
        shell: bash
        run: vercel deploy --prebuilt ${{ inputs.production && '--prod' }} --token="$VERCEL_TOKEN"
